### ISSUE TITLE
ECONNREFUSED not handled

### ISSUE THREAD

**Issue by lobando** [ibm-messaging/iot-nodejs#7]
Not sure if this is the expected behaviour but the library is not handling an ECONNREFUSED error and it's throwing out the exception (crashing the app). I used to be able to handle anything with an on 'error' callback.. but those are no longer supported.

```
[2015-12-04 21:11:26.487] [ERROR] [default] - Connection Error :: Error: connect ECONNREFUSED XXX.XXX.XXX.XXX:8883
/usr/src/myapp/node_modules/ibmiotf/lib/IotfApplication.js:189
		throw new Error(err);
		^

Error: Error: connect ECONNREFUSED XXX.XXX.XXX.XXX:8883
    at MqttClient.<anonymous> (/usr/src/myapp/node_modules/ibmiotf/lib/IotfApplication.js:189:9)
    at emitOne (events.js:77:13)
    at MqttClient.emit (events.js:169:7)
    at TLSSocket.handleTLSerrors (/usr/src/myapp/node_modules/ibmiotf/node_modules/mqtt/lib/connect/tls.js:32:18)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

**Comment by jeffdare** [comment]
Hi,

This whole package was revamped with browserify. So now there is new event "error" emitted when an error occurs. 
Please try this with the new node package(0.2.0).

Thanks!!

**Comment by lobando** [comment]
I'm getting an error when try to get the package with npm

`npm ERR! version not found: ibmiotf@0.2.0`

**Comment by jeffdare** [comment]
Hi,

If you run *npm install ibmiotf*, you should get the latest version. Or run *npm update* on the existing repo to get the latest version. 
Thanks!

**Comment by lobando** [comment]
Jeff, 
Thanks I was able to get the latest version but I have some issues.
It keeps connecting and disconnecting from the IoTF,  I'm connecting as an application.
The problem is worse because I can't go back to the old version now, It seems that some dependencies have changed and the old version is showing the same behaviour.

Please advice,

Thanks

Luis
